# Generated by Django 4.2.13 on 2024-06-26 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("center", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("name_sa", models.CharField(editable=False, max_length=100)),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=80,
                        null=True,
                        verbose_name="short name",
                    ),
                ),
                (
                    "id_card",
                    models.CharField(blank=True, max_length=30, verbose_name="id card"),
                ),
                (
                    "birth",
                    models.DateField(blank=True, null=True, verbose_name="birth"),
                ),
                (
                    "person_type",
                    models.CharField(
                        choices=[
                            ("PUP", "pupil"),
                            ("WEB", "web pupil"),
                            ("GST", "gest"),
                        ],
                        default="PUP",
                        max_length=3,
                        verbose_name="type",
                    ),
                ),
                (
                    "aspect",
                    models.CharField(
                        choices=[
                            ("21", "Project 21"),
                            ("A1", "1st. Aspect"),
                            ("A2", "2nd. Aspect"),
                            ("A3", "3rd. Aspect"),
                            ("A4", "4th. Aspect"),
                            ("GR", "Grail"),
                            ("A5", "5th. Aspect"),
                            ("A6", "6th. Aspect"),
                        ],
                        default="--",
                        max_length=2,
                        verbose_name="aspect",
                    ),
                ),
                (
                    "aspect_date",
                    models.DateField(blank=True, null=True, verbose_name="date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACT", "active"),
                            ("LIC", "licensed"),
                            ("DEA", "dead"),
                            ("DIS", "disconnected"),
                            ("REM", "removed"),
                        ],
                        default="ACT",
                        max_length=3,
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="observations"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="center.center",
                        verbose_name="center",
                    ),
                ),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="made_by_person",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "person",
                "verbose_name_plural": "people",
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                (
                    "birth",
                    models.DateField(blank=True, null=True, verbose_name="birth"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "male"),
                            ("F", "female"),
                            ("-", "do not inform"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="gender",
                    ),
                ),
                (
                    "id_card",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="id card"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="address"
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, max_length=25, verbose_name="number"),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="complement"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="district"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="city"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=2, null=True, verbose_name="state"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("BR", "Brazil")],
                        default="BR",
                        max_length=2,
                        verbose_name="country",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(blank=True, max_length=15, verbose_name="zip"),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "sos_contact",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="emergency contact",
                    ),
                ),
                (
                    "sos_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="emergency phone",
                    ),
                ),
                ("historic", jsonfield.fields.JSONField(blank=True, null=True)),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="observations"),
                ),
                ("migration", models.BooleanField(default=False)),
                ("sign_lgpd", models.BooleanField(default=False)),
                (
                    "invited_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="invited on"
                    ),
                ),
                ("imported", models.BooleanField(default=False)),
                (
                    "imported_on",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="imported on"
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="center.center",
                        verbose_name="center",
                    ),
                ),
            ],
            options={
                "verbose_name": "invitation",
                "verbose_name_plural": "invitations",
            },
        ),
        migrations.CreateModel(
            name="Historic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurrence",
                    models.CharField(
                        choices=[
                            ("OTH", "other"),
                            ("TRF", "transfer"),
                            ("ACT", "active"),
                            ("LIC", "licensed"),
                            ("DEA", "dead"),
                            ("DIS", "disconnected"),
                            ("REM", "removed"),
                            ("21", "Project 21"),
                            ("A1", "1st. Aspect"),
                            ("A2", "2nd. Aspect"),
                            ("A3", "3rd. Aspect"),
                            ("A4", "4th. Aspect"),
                            ("GR", "Grail"),
                            ("A5", "5th. Aspect"),
                            ("A6", "6th. Aspect"),
                        ],
                        default="ACT",
                        max_length=3,
                        verbose_name="occurrence",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="date")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="made_by_historic",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="person.person",
                        verbose_name="person",
                    ),
                ),
            ],
            options={
                "verbose_name": "historic",
                "verbose_name_plural": "historics",
            },
        ),
    ]
