# Generated by Django 3.2.7 on 2021-10-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_alter_person_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_card',
            field=models.CharField(blank=True, max_length=30, verbose_name='id card'),
        ),
    ]
