# Generated by Django 3.2.14 on 2022-08-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20220809_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='birth'),
        ),
    ]
