# Generated by Django 3.2.14 on 2022-08-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0010_alter_person_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='reg',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='reg'),
        ),
    ]
