# Generated by Django 3.2.14 on 2022-08-09 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_alter_person_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='occurrence',
            field=models.CharField(choices=[('TRF', 'transfered'), ('RGS', 'regressed'), ('OTH', 'other'), ('PRP', 'preparatório'), ('PRB', 'probatório'), ('PRF', 'professo'), ('--', '--'), ('A1', '1st. Aspect'), ('A2', '2nd. Aspect'), ('A3', '3rd. Aspect'), ('A4', '4th. Aspect'), ('GR', 'Grail'), ('A5', '5th. Aspect'), ('A6', '6th. Aspect'), ('---', '---'), ('ACT', 'active'), ('LIC', 'licensed'), ('DEA', 'dead'), ('DIS', 'disconnected'), ('REM', 'removed')], default='ACT', max_length=3, verbose_name='occurrence'),
        ),
        migrations.AlterField(
            model_name='historic',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person', verbose_name='person'),
        ),
    ]
