# Generated by Django 3.2.15 on 2022-08-14 13:08

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_auto_20220809_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempRegOfPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('birth', models.DateField(verbose_name='birth')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('-', 'do not inform')], default='-', max_length=1, verbose_name='gender')),
                ('id_card', models.CharField(max_length=30, verbose_name='id card')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('state', models.CharField(max_length=2, verbose_name='state')),
                ('country', models.CharField(choices=[('BR', 'Brazil')], default='BR', max_length=2, verbose_name='country')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(max_length=254)),
                ('solicited_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='solicited on')),
            ],
            options={
                'verbose_name': 'temporary registration of person',
                'verbose_name_plural': 'temporary registration of persons',
            },
        ),
    ]
