# Generated by Django 3.2.15 on 2022-08-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0013_tempregofperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempregofperson',
            name='birth',
            field=models.DateField(blank=True, null=True, verbose_name='birth'),
        ),
        migrations.AlterField(
            model_name='tempregofperson',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='tempregofperson',
            name='id_card',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='id card'),
        ),
        migrations.AlterField(
            model_name='tempregofperson',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='tempregofperson',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='state'),
        ),
    ]
