# Generated by Django 3.2.15 on 2022-08-16 09:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0010_remove_center_secretary'),
        ('person', '0016_tempregofperson_imported'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, verbose_name='name')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='birth')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('-', 'do not inform')], default='-', max_length=1, verbose_name='gender')),
                ('id_card', models.CharField(blank=True, max_length=30, null=True, verbose_name='id card')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='city')),
                ('state', models.CharField(blank=True, max_length=2, null=True, verbose_name='state')),
                ('country', models.CharField(choices=[('BR', 'Brazil')], default='BR', max_length=2, verbose_name='country')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('email', models.EmailField(max_length=254)),
                ('invited_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='invited on')),
                ('imported', models.BooleanField(default=False)),
                ('center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='center.center', verbose_name='center')),
            ],
            options={
                'verbose_name': 'temporary registration of person',
                'verbose_name_plural': 'temporary registration of persons',
            },
        ),
        migrations.DeleteModel(
            name='TempRegOfPerson',
        ),
    ]
