# Generated by Django 3.2.15 on 2022-08-17 09:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0018_alter_invitation_invited_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='invited_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='invited on'),
        ),
    ]
