# Generated by Django 3.2.15 on 2022-08-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0019_alter_invitation_invited_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='sos_contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='emergency contact'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sos_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='emergency phone'),
        ),
    ]
