# Generated by Django 3.2.15 on 2022-08-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0021_alter_invitation_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='sos_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='emergency contact'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='sos_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='emergency phone'),
        ),
    ]
