# Generated by Django 3.2.15 on 2022-08-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0022_auto_20220821_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'male'), ('F', 'female'), ('-', 'do not inform')], max_length=1, null=True, verbose_name='gender'),
        ),
    ]
