# Generated by Django 3.2.15 on 2022-08-22 13:43

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0024_invitation_historic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='historic',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
