# Generated by Django 3.2.15 on 2022-08-23 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0025_alter_invitation_historic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'person', 'verbose_name_plural': 'people'},
        ),
    ]
