# Generated by Django 3.2.15 on 2022-08-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0026_alter_person_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='imported_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='imported on'),
        ),
    ]
