# Generated by Django 3.2.15 on 2022-08-31 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0027_invitation_imported_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'verbose_name': 'temporary registration of person', 'verbose_name_plural': 'temporary registration of pupil'},
        ),
    ]
