# Generated by Django 3.2.15 on 2022-09-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0031_alter_invitation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='observations',
            field=models.TextField(blank=True, verbose_name='observations'),
        ),
    ]
