# Generated by Django 4.2.7 on 2023-12-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0034_remove_person_reg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historic",
            name="occurrence",
            field=models.CharField(
                choices=[
                    ("OTH", "other"),
                    ("TRF", "transfer"),
                    ("ACT", "active"),
                    ("LIC", "licensed"),
                    ("DEA", "dead"),
                    ("DIS", "disconnected"),
                    ("REM", "removed"),
                    ("A1", "1st. Aspect"),
                    ("A2", "2nd. Aspect"),
                    ("A3", "3rd. Aspect"),
                    ("A4", "4th. Aspect"),
                    ("GR", "Grail"),
                    ("A5", "5th. Aspect"),
                    ("A6", "6th. Aspect"),
                ],
                default="ACT",
                max_length=3,
                verbose_name="occurrence",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="aspect",
            field=models.CharField(
                choices=[
                    ("A1", "1st. Aspect"),
                    ("A2", "2nd. Aspect"),
                    ("A3", "3rd. Aspect"),
                    ("A4", "4th. Aspect"),
                    ("GR", "Grail"),
                    ("A5", "5th. Aspect"),
                    ("A6", "6th. Aspect"),
                ],
                default="--",
                max_length=2,
                verbose_name="aspect",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACT", "active"),
                    ("LIC", "licensed"),
                    ("DEA", "dead"),
                    ("DIS", "disconnected"),
                    ("REM", "removed"),
                ],
                default="ACT",
                max_length=3,
            ),
        ),
    ]
