# Generated by Django 4.2.13 on 2024-06-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("person", "0035_alter_historic_occurrence_alter_person_aspect_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historic",
            name="occurrence",
            field=models.CharField(
                choices=[
                    ("OTH", "other"),
                    ("TRF", "transfer"),
                    ("ACT", "active"),
                    ("LIC", "licensed"),
                    ("DEA", "dead"),
                    ("DIS", "disconnected"),
                    ("REM", "removed"),
                    ("21", "Project 21"),
                    ("A1", "1st. Aspect"),
                    ("A2", "2nd. Aspect"),
                    ("A3", "3rd. Aspect"),
                    ("A4", "4th. Aspect"),
                    ("GR", "Grail"),
                    ("A5", "5th. Aspect"),
                    ("A6", "6th. Aspect"),
                ],
                default="ACT",
                max_length=3,
                verbose_name="occurrence",
            ),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="address",
            field=models.CharField(blank=True, max_length=100, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="number",
            field=models.CharField(blank=True, max_length=25, verbose_name="number"),
        ),
        migrations.AlterField(
            model_name="person",
            name="aspect",
            field=models.CharField(
                choices=[
                    ("21", "Project 21"),
                    ("A1", "1st. Aspect"),
                    ("A2", "2nd. Aspect"),
                    ("A3", "3rd. Aspect"),
                    ("A4", "4th. Aspect"),
                    ("GR", "Grail"),
                    ("A5", "5th. Aspect"),
                    ("A6", "6th. Aspect"),
                ],
                default="--",
                max_length=2,
                verbose_name="aspect",
            ),
        ),
    ]
