# Generated by Django 3.2.16 on 2022-11-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20220809_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequency',
            name='ranking',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('OPN', 'opened'), ('CLS', 'closed')], default='OPN', max_length=3),
        ),
    ]
