# Generated by Django 4.2.7 on 2023-12-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0008_auto_20221121_0831"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="qr_code",
        ),
        migrations.AlterField(
            model_name="frequency",
            name="aspect",
            field=models.CharField(
                choices=[
                    ("A1", "1st. Aspect"),
                    ("A2", "2nd. Aspect"),
                    ("A3", "3rd. Aspect"),
                    ("A4", "4th. Aspect"),
                    ("GR", "Grail"),
                    ("A5", "5th. Aspect"),
                    ("A6", "6th. Aspect"),
                ],
                default="--",
                max_length=2,
                verbose_name="aspect",
            ),
        ),
    ]
