# Generated by Django 3.2.14 on 2022-08-09 18:26

from django.db import migrations, models
import django.db.models.deletion
import apps.treasury.models


class Migration(migrations.Migration):

    dependencies = [
        ("center", "0010_remove_center_secretary"),
        ("event", "0007_auto_20220809_1419"),
        ("person", "0012_auto_20220809_1525"),
        ("treasury", "0003_alter_order_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="paytypes",
            options={
                "verbose_name": "pay type",
                "verbose_name_plural": "pay types",
            },
        ),
        migrations.AlterField(
            model_name="bankflags",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="bankflags",
            name="name",
            field=models.CharField(max_length=15, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="formofpayment",
            name="bank_flag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.bankflags",
                verbose_name="bank flag",
            ),
        ),
        migrations.AlterField(
            model_name="formofpayment",
            name="complement",
            field=models.CharField(
                blank=True, max_length=36, null=True, verbose_name="complement"
            ),
        ),
        migrations.AlterField(
            model_name="formofpayment",
            name="ctrl_number",
            field=models.CharField(
                blank=True,
                max_length=36,
                null=True,
                verbose_name="control number",
            ),
        ),
        migrations.AlterField(
            model_name="formofpayment",
            name="payform_type",
            field=models.CharField(
                choices=[
                    ("PIX", "pix"),
                    ("CSH", "cash"),
                    ("CHK", "check"),
                    ("PRE", "pre check"),
                    ("DBT", "debit"),
                    ("CDT", "credit"),
                    ("DPT", "deposit"),
                    ("TRF", "transfer"),
                    ("SLP", "bank slip"),
                ],
                default="CSH",
                max_length=3,
                verbose_name="type",
            ),
        ),
        migrations.AlterField(
            model_name="formofpayment",
            name="value",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="value"
            ),
        ),
        migrations.AlterField(
            model_name="formofpayment",
            name="voucher_img",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.treasury.models.voucher_img_filename,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="amount"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="center.center",
                verbose_name="center",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="description",
            field=models.CharField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="description",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="form_of_payments",
            field=models.ManyToManyField(
                to="treasury.FormOfPayment", verbose_name="form of payments"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payments",
            field=models.ManyToManyField(
                to="treasury.Payment", verbose_name="payments"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="person.person",
                verbose_name="person",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="self_payed",
            field=models.BooleanField(
                default=False, verbose_name="self payed"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="event.event",
                verbose_name="event",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="obs",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="observations",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paytype",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="treasury.paytypes",
                verbose_name="pay type",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="person.person",
                verbose_name="person",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="ref_month",
            field=models.DateField(
                blank=True, null=True, verbose_name="reference month"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="value",
            field=models.DecimalField(
                decimal_places=2, max_digits=6, verbose_name="value"
            ),
        ),
        migrations.AlterField(
            model_name="paytypes",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="paytypes",
            name="name",
            field=models.CharField(max_length=50, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="paytypes",
            name="pay_type",
            field=models.CharField(
                choices=[
                    ("MON", "monthly"),
                    ("EVE", "by event"),
                    ("CAM", "campaign"),
                ],
                default="MON",
                max_length=3,
                verbose_name="type",
            ),
        ),
    ]
