# Generated by Django 4.2.13 on 2024-06-26 11:34

import apps.publicwork.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("center", "0001_initial"),
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("CTT", "contact"), ("MET", "meeting")],
                        default="CTT",
                        max_length=3,
                        verbose_name="type",
                    ),
                ),
                ("theme", models.CharField(max_length=100, verbose_name="theme")),
                ("date", models.DateField(blank=True, null=True, verbose_name="date")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="center.center",
                        verbose_name="center",
                    ),
                ),
            ],
            options={
                "verbose_name": "lecture",
                "verbose_name_plural": "lectures",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="TempRegOfSeeker",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                ("birth", models.DateField(verbose_name="birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "male"),
                            ("F", "female"),
                            ("-", "do not inform"),
                        ],
                        default="M",
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default_profile.jpg",
                        upload_to=apps.publicwork.models.temp_reg_of_seeker_pics,
                        verbose_name="image",
                    ),
                ),
                ("city", models.CharField(max_length=50, verbose_name="city")),
                ("state", models.CharField(max_length=2, verbose_name="state")),
                (
                    "country",
                    models.CharField(
                        choices=[("BR", "Brazil")],
                        default="BR",
                        max_length=2,
                        verbose_name="country",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="phone")),
                ("email", models.EmailField(max_length=254)),
                (
                    "solicited_on",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="solicited on"
                    ),
                ),
            ],
            options={
                "verbose_name": "temporary registration of seeker",
                "verbose_name_plural": "temporary registration of seekers",
            },
        ),
        migrations.CreateModel(
            name="Seeker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="name")),
                ("name_sa", models.CharField(editable=False, max_length=80)),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=40, null=True, verbose_name="short name"
                    ),
                ),
                (
                    "birth",
                    models.DateField(blank=True, null=True, verbose_name="birth"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "male"),
                            ("F", "female"),
                            ("-", "do not inform"),
                        ],
                        default="M",
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="default_profile.jpg",
                        upload_to=apps.publicwork.models.seeker_pics,
                        verbose_name="image",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=50, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=2, verbose_name="state"),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("BR", "Brazil")],
                        default="BR",
                        max_length=2,
                        verbose_name="country",
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("OBS", "observation"),
                            ("NEW", "new"),
                            ("MBR", "member"),
                            ("INS", "installing"),
                            ("ITD", "installed"),
                            ("STD", "stand by"),
                            ("RST", "restriction"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "status_date",
                    models.DateField(blank=True, null=True, verbose_name="status date"),
                ),
                (
                    "observations",
                    models.TextField(blank=True, verbose_name="observations"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="center.center",
                        verbose_name="center",
                    ),
                ),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="made_by_seeker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "seeker",
                "verbose_name_plural": "seekers",
            },
        ),
        migrations.CreateModel(
            name="PublicworkGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="center.center",
                        verbose_name="center",
                    ),
                ),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="made_by_publicwork_group",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        blank=True, to="publicwork.seeker", verbose_name="members"
                    ),
                ),
                (
                    "mentors",
                    models.ManyToManyField(
                        blank=True, to="person.person", verbose_name="mentors"
                    ),
                ),
            ],
            options={
                "verbose_name": "publicwork group",
                "verbose_name_plural": "publicwork groups",
            },
        ),
        migrations.CreateModel(
            name="Listener",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observations",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="observations",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="publicwork.lecture",
                        verbose_name="lecture",
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="publicwork.seeker",
                        verbose_name="seeker",
                    ),
                ),
            ],
            options={
                "verbose_name": "listener",
                "verbose_name_plural": "listeners",
            },
        ),
        migrations.AddField(
            model_name="lecture",
            name="listeners",
            field=models.ManyToManyField(
                blank=True,
                through="publicwork.Listener",
                to="publicwork.seeker",
                verbose_name="listeners",
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="made_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_lecture",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="HistoricOfSeeker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurrence",
                    models.CharField(
                        choices=[
                            ("OBS", "observation"),
                            ("NEW", "new"),
                            ("MBR", "member"),
                            ("INS", "installing"),
                            ("ITD", "installed"),
                            ("STD", "stand by"),
                            ("RST", "restriction"),
                        ],
                        default="MBR",
                        max_length=3,
                        verbose_name="occurrence",
                    ),
                ),
                ("date", models.DateField(blank=True, null=True, verbose_name="date")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="description",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "made_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="made_by_historic_of_seeker",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seeker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="publicwork.seeker",
                        verbose_name="seeker",
                    ),
                ),
            ],
            options={
                "verbose_name": "historic",
                "verbose_name_plural": "historics",
            },
        ),
    ]
