# Generated by Django 3.2.5 on 2021-08-01 20:27

from django.db import migrations, models
import apps.publicwork.models


class Migration(migrations.Migration):

    dependencies = [
        ("publicwork", "0015_auto_20210715_0735"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicofseeker",
            name="occurrence",
            field=models.CharField(
                choices=[
                    ("OBS", "observation"),
                    ("NEW", "new"),
                    ("MBR", "member"),
                    ("RCP", "reception"),
                    ("INS", "installing"),
                    ("RST", "restriction"),
                ],
                default="MBR",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="seeker",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_profile.jpg",
                upload_to=apps.publicwork.models.seeker_pics,
            ),
        ),
        migrations.AlterField(
            model_name="seeker",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OBS", "observation"),
                    ("NEW", "new"),
                    ("MBR", "member"),
                    ("RCP", "reception"),
                    ("INS", "installing"),
                    ("RST", "restriction"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="tempregofseeker",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_profile.jpg",
                upload_to=apps.publicwork.models.seeker_pics,
            ),
        ),
    ]
