# Generated by Django 3.2.16 on 2022-11-21 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicwork', '0018_auto_20220809_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listener',
            name='ranking',
        ),
    ]
