# Generated by Django 4.2.7 on 2023-12-04 20:42

import apps.publicwork.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publicwork", "0019_remove_listener_ranking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tempregofseeker",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default_profile.jpg",
                upload_to=apps.publicwork.models.temp_reg_of_seeker_pics,
                verbose_name="image",
            ),
        ),
    ]
