# Generated by Django 3.2.14 on 2022-08-10 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0012_auto_20220809_1525'),
        ('center', '0010_remove_center_secretary'),
        ('workgroup', '0005_alter_workgroup_aspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person', verbose_name='person'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='workgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workgroup.workgroup', verbose_name='workgroup'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='center.center', verbose_name='center'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='members',
            field=models.ManyToManyField(through='workgroup.Membership', to='person.Person', verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='workgroup',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
