# Generated by Django 4.2.7 on 2023-12-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workgroup", "0006_auto_20220810_1304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workgroup",
            name="aspect",
            field=models.CharField(
                choices=[
                    ("A1", "1st. Aspect"),
                    ("A2", "2nd. Aspect"),
                    ("A3", "3rd. Aspect"),
                    ("A4", "4th. Aspect"),
                    ("GR", "Grail"),
                    ("A5", "5th. Aspect"),
                    ("A6", "6th. Aspect"),
                ],
                default="--",
                max_length=2,
            ),
        ),
    ]
