# Generated by Django 3.2.12 on 2022-03-14 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('center', '0005_alter_center_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(choices=[('BDG', 'BADGE')], default='BDG', max_length=3)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='center.center')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'responsible',
                'verbose_name_plural': 'responsibles',
            },
        ),
        migrations.AddField(
            model_name='center',
            name='responsible_for',
            field=models.ManyToManyField(blank=True, through='center.Responsible', to=settings.AUTH_USER_MODEL),
        ),
    ]
