# Generated by Django 3.2.12 on 2022-04-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0006_auto_20220314_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsible',
            name='rule',
            field=models.CharField(choices=[('BDG', 'Badge')], default='BDG', max_length=3),
        ),
    ]
