# Generated by Django 3.2.13 on 2022-07-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0009_auto_20220718_0404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='secretary',
        ),
    ]
