# Generated by Django 3.2.15 on 2022-10-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("center", "0010_remove_center_secretary"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="accommodation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="center",
            name="mentoring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="center",
            name="publicwork",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="center",
            name="treasury",
            field=models.BooleanField(default=False),
        ),
    ]
