# Generated by Django 4.2.13 on 2024-06-26 11:34

import apps.user.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Enter a valid email.  <<REQUIRED>>",
                        max_length=255,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active.                     Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social_name",
                    models.CharField(max_length=80, verbose_name="social name"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "male"),
                            ("F", "female"),
                            ("-", "do not inform"),
                        ],
                        default="M",
                        max_length=1,
                        verbose_name="gender",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default_profile.jpg",
                        upload_to=apps.user.models.profile_pics,
                        verbose_name="image",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="address"
                    ),
                ),
                (
                    "number",
                    models.CharField(blank=True, max_length=25, verbose_name="number"),
                ),
                (
                    "complement",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="complement"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="district"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=50, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(blank=True, max_length=2, verbose_name="state"),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[("BR", "Brazil")],
                        default="BR",
                        max_length=2,
                        verbose_name="country",
                    ),
                ),
                (
                    "zip_code",
                    models.CharField(blank=True, max_length=15, verbose_name="zip"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="phone"),
                ),
                (
                    "sos_contact",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="emergency contact"
                    ),
                ),
                (
                    "sos_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="emergency phone"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "profile",
                "verbose_name_plural": "profiles",
            },
        ),
    ]
