# Generated by Django 3.2.14 on 2022-08-08 18:20

from django.db import migrations, models
import apps.user.models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_profile_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="marital_status",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone_2",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="profession",
        ),
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="address"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="city"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="complement",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="complement"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(
                choices=[("BR", "Brazil")],
                default="BR",
                max_length=2,
                verbose_name="country",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="district",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="district"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("M", "male"),
                    ("F", "female"),
                    ("-", "do not inform"),
                ],
                default="M",
                max_length=1,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="default_profile.jpg",
                upload_to=apps.user.models.profile_pics,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="number",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="number"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="social_name",
            field=models.CharField(max_length=80, verbose_name="social name"),
        ),
    ]
