# Generated by Django 3.2.14 on 2022-08-08 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220808_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_1',
            new_name='phone',
        ),
    ]
