# Generated by Django 4.2.13 on 2024-06-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0007_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.CharField(blank=True, max_length=100, verbose_name="address"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="number",
            field=models.CharField(blank=True, max_length=25, verbose_name="number"),
        ),
    ]
